silex/blog/src/Entity/Article.php
<?php
/**
 * Created by PhpStorm.
 * User: Hello
 * Date: 03/08/2017
 * Time: 16:29
 */

namespace Entity;


class Article
{
    /**
     * @var
     */
    private $id;

    /**
     * @var
     */
    private $title;

    /**
     * @var
     */
    private $header;

    /**
     * @var
     */
    private $content;

    /**
     * @var
     */
    private $category;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Article
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     * @return Article
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * @param mixed $header
     * @return Article
     */
    public function setHeader($header)
    {
        $this->header = $header;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param mixed $content
     * @return Article
     */
    public function setContent($content)
    {
        $this->content = $content;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     * @return Article
     */
    public function setCategory(Category $category)
    {
        $this->category = $category;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getCategoryId(){
        if(!is_null($this->category)){
            return $this->category->getId();
        }
    }

    /**
     * @return string
     */
    public function getCategoryName(){
        if(!is_null($this->category)){
            return $this->category->getName();
        }

        return '';
    }


}

silex/blog/src/Controller/Admin/ArticleController.php
<?php
/**
 * Created by PhpStorm.
 * User: Hello
 * Date: 03/08/2017
 * Time: 16:22
 */

namespace Controller\Admin;


use Controller\ControllerAbstract;
use Entity\Article;
use Entity\Category;
use Symfony\Component\HttpFoundation\Request;

class ArticleController extends ControllerAbstract
{

    public function listAction(){
        $articles = $this->app['article.repository']->findAll();
        return $this->render('admin/article/list.html.twig',
            [
                'articles' => $articles
            ]
        );
    }

    public function editAction(Request $request,$id = null){

        if($id == true){
            // on va chercher l'article en bdd
            $article = $this->app['article.repository']->find($id);

            if(!$article instanceof Article){
                $this->app->abort(404);
            }
        }else{
            // nouvelle article
            $article = new Article();
            // on créer un nouvelle category que l'on enregistre dans article($category)
            $article->setCategory(new Category());
        }

        $categories = $this->app['category.repository']->findAll();
        $errors = [];

        if($request->isMethod('POST')){
            $article->setTitle($request->request->get('title'));  // $_POST[title]
            $article->setHeader($request->request->get('header'));
            $article->setContent($request->request->get('content'));
            $article->getCategory()->setId($request->request->get('category'));

            if(empty($_POST['title'])){
                $errors['title'] = 'Le titre est obligatoire';
            }elseif(strlen($_POST['title']) > 100){
                $errors['title'] = 'Le titre ne doit pas faire plus de 100 caractères';
            }

            if(empty($_POST['header'])) {
                $errors['header'] = 'Le header est obligatoire';
            }

            if(empty($_POST['content'])) {
                $errors['content'] = 'Le Contenu est obligatoire';
            }

            if(empty($_POST['category'])) {
                $errors['category'] = 'La rubrique est obligatoire';
            }

            if(empty($errors)){
                $this->app['article.repository']->save($article);
                if($id == true){
                     $this->addFlashMessage('L\' article est modifié');
                }else{
                    $this->addFlashMessage('L\' article est enregistré');
                }
                return $this->redirectRoute('admin_articles');
            }else {
                $message = '<strong>Le formulaire contient des erreurs :</strong>';
                $message .= '<br>' . implode('<br>', $errors);
                $this->addFlashMessage($message, 'error');
            }
        }

        return $this->render('admin/article/edit.html.twig',
            [
                'article' => $article,
                'categories' => $categories
            ]
        );

        //return $this->render('admin/article/edit.html.twig');
    }

    public function deleteAction($id){
        // on va chercher l'article en bdd
        $article = $this->app['article.repository']->find($id);

        if(!$article instanceof Article){
            $this->app->abort(404);
        }

        $this->app['article.repository']->delete($article);

        $this->addFlashMessage('L\' article  est supprimée');

        return $this->redirectRoute('admin_articles');
    }
}

silex/blog/templates/article/article.html.twig
{% extends "layout.html.twig" %}

{% block title article.title %}

{% block content %}
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="page-header">
                        <h1>{{ article.title }}</h1>
                    </div>
                    <img src="http://cdn2-europe1.new2.ladmedia.fr/var/europe1/storage/images/europe1/sport/foot-une-superligue-europeenne-est-ce-credible-2667823/25729087-1-fre-FR/Foot-une-Superligue-europeenne-est-ce-credible.jpg" alt="" class="Responsive image" width="800">
                    <h3>{{ article.header }}</h3>
                    <p>Categorie :
                        <a href="{{ path('category', {category : article.categoryName }) }}"><small class="label label-primary">{{ article.categoryName }}</small></a>
                    </p>
                    <p>{{ article.content }}</p>
                </div>
            </div>
            <div class="page-header">
                <h2>Commentaires (3)</h2>
            </div>
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="http://www.journaldugeek.com/files/2014/04/infographie_profil_internautes_europ%C3%A9ens-600x375.jpg" alt="" width="64" height="64">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Larson</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor dolores eaque est facilis illo magnam mollitia nam numquam, officia perferendis praesentium quaerat repellat reprehenderit suscipit vero. Enim facilis neque sequi.</p>
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="https://pixabay.com/get/eb36b5062afc093ed1534705fb0938c9bd22ffd41cb1104993f0c479af/profile-2349288_1920.jpg" alt="" width="64" height="64">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">grolland</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor dolores eaque est facilis illo magnam mollitia nam numquam, officia perferendis praesentium quaerat repellat reprehenderit suscipit vero. Enim facilis neque sequi.</p>
                </div>
            </div><!-- media -->
            <div class="page-header">
                <h3>Nouveau Commentaire</h3>
            </div>
            <form action="">
                <div class="form-group">
                    <textarea class="form-control" name="" id="" cols="30" rows="7"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Enregistrer</button>
            </form>
        </div><!-- col-9 -->

        <div class="col-md-3">
            <div class="page-header">
                <h2>Autres Articles</h2>
            </div>
            {% for article in articles %}
            <a href="{{ path('article', { id: article.id}) }}">
                <div class="thumbnail">
                    <img src="http://www.actu-malin.fr/wp-content/uploads/2014/10/voyage.jpg" alt="" class="Responsive image" >
                    <div class="caption">
                        <h3>{{ article.title[:40] }}...</h3>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}